/**
 * seed_firestore.js
 * Pobla el Firestore del proyecto "misteriosdechile" con las 80 cartas.
 *
 * INSTRUCCIONES:
 * 1. Instala dependencias:
 *      npm install firebase-admin
 * 2. Descarga la clave de servicio desde Firebase Console:
 *      Configuración del proyecto → Cuentas de servicio → Generar nueva clave privada
 *      Guarda el archivo como "serviceAccountKey.json" en la misma carpeta que este script
 * 3. Ejecuta:
 *      node seed_firestore.js
 */

const admin = require("firebase-admin");

admin.initializeApp({
  credential: admin.credential.applicationDefault(),
  projectId: "misteriosdechile-7a538",
});

const db = admin.firestore();

// ── DATOS ────────────────────────────────────────────────────────────────────

const baseNombres = {
  "01": "id_01_expedicion_almagro",
  "02": "id_02_fundacion_de_santiago",
  "03": "id_03_destruccion_de_santiago",
  "04": "id_04_fundacion_de_concepcion",
  "05": "id_05_batalla_de_tucapel",
  "06": "id_06_batalla_de_lagunillas",
  "07": "id_07_desastre_de_curalaba",
  "08": "id_08_real_situado",
  "09": "id_09_esclavitud_indigena",
  "10": "id_10_parlamento_de_quilin",
  "11": "id_11_el_terremoto_magno",
  "12": "id_12_el_inquilino",
  "13": "id_13_expulsion_jesuita",
  "14": "id_14_abolicion_encomienda",
  "15": "id_15_camino_santiago_valparaiso",
  "16": "id_16_primera_junta_de_gobierno",
  "17": "id_17_primer_congreso_nacional",
  "18": "id_18_libertad_de_vientres",
  "19": "id_19_la_aurora_de_chile",
  "20": "id_20_reglamento_constitucional",
  "21": "id_21_instituto_nacional",
  "22": "id_22_desastre_de_rancagua",
  "23": "id_23_los_talavera",
  "24": "id_24_manuel_rodriguez",
  "25": "id_25_batalla_de_chacabuco",
  "26": "id_26_proclamacion_independencia",
  "27": "id_27_batalla_de_maipu",
  "28": "id_28_toma_de_valdivia",
  "29": "id_29_abdicacion_de_ohiggins",
  "30": "id_30_abolicion_esclavitud",
  "31": "id_31_constitucion_moralista",
  "32": "id_32_leyes_federales",
  "33": "id_33_tratado_de_tantauco",
  "34": "id_34_constitucion_liberal",
  "35": "id_35_batalla_lircay",
  "36": "id_36_el_peso_de_la_noche",
  "37": "id_37_descubrimiento_chanarcillo",
  "38": "id_38_constitucion_de_1833",
  "39": "id_39_guerra_confederacion",
  "40": "id_40_batalla_de_yungay",
  "41": "id_41_ley_de_colonizacion",
  "42": "id_42_toma_del_estrecho",
  "43": "id_43_universidad_de_chile",
  "44": "id_44_reconocimiento_espana",
  "45": "id_45_codigo_civil",
  "46": "id_46_primer_ferrocarril",
  "47": "id_47_revolucion_1851",
  "48": "id_48_el_telegrafo",
  "49": "id_49_cuestion_del_sacristan",
  "50": "id_50_ley_instruccion_primaria",
  "51": "id_51_fusion_liberal_conservadora",
  "52": "id_52_el_cuerpo_de_bomberos",
  "53": "id_53_guerra_contra_espana",
  "54": "id_54_fin_reeleccion_inmediata",
  "55": "id_55_reforma_electoral",
  "56": "id_56_decreto_amunategui",
  "57": "id_57_guerra_del_pacifico",
  "58": "id_58_combate_de_angamos",
  "59": "id_59_tratado_de_limites",
  "60": "id_60_toma_de_lima",
  "61": "id_61_batalla_de_concepcion",
  "62": "id_62_ley_de_cementerios",
  "63": "id_63_ley_atrimonio_civil",
  "64": "id_64_ley_registro_civil",
  "65": "id_65_anexion_isla_de_pascua",
  "66": "id_66_universidad_catolica",
  "67": "id_67_el_viaducto_del_malleco",
  "68": "id_68_guerra_civil_de_1981",
  "69": "id_69_batalalla_de_placilla",
  "70": "id_70_lacomuna_autonoma",
  "71": "id_71_alumbrado_electrico",
  "72": "id_72_cine_en_chile",
  "73": "id_73_el_travia_electrico",
  "74": "id_74_matanza_escuela_santa_maria",
  "75": "id_75_centenario_de_chile",
  "76": "id_76_combate_naval_de_iquique",
  "77": "id_77_cuestion_social",
  "78": "id_78_constitucion_moralista_1823",
  "79": "id_79_constitucion_liberal_1828",
  "80": "id_80_constitucion_de_1833",
};

const eventosData = {
  "01": "Expedición de Almagro",
  "02": "Fundación de Santiago",
  "03": "Destrucción de Santiago",
  "04": "Fundación de Concepción",
  "05": "Batalla de Tucapel",
  "06": "Batalla de Lagunillas",
  "07": "Desastre de Curalaba",
  "08": "Real Situado",
  "09": "Esclavitud Indígena",
  "10": "Parlamento de Quilín",
  "11": "El Terremoto Magno",
  "12": "El Inquilino",
  "13": "Expulsión Jesuitas",
  "14": "Abolición Encomienda",
  "15": "Camino Santiago-Valparaíso",
  "16": "Primera Junta de Gobierno",
  "17": "Primer Congreso Nacional",
  "18": "Libertad de Vientre",
  "19": "La Aurora de Chile",
  "20": "Reglamento Constitucional",
  "21": "Fundación Inst. Nacional",
  "22": "Desastre de Rancagua",
  "23": "Los Talaveras",
  "24": "Espionaje Patriota",
  "25": "Batalla de Chacabuco",
  "26": "Proclamación Independencia",
  "27": "Batalla de Maipú",
  "28": "Toma de Valdivia",
  "29": "Abdicación de OHiggins",
  "30": "Abolición Esclavitud",
  "31": "Constitución Moralista",
  "32": "Leyes Federales",
  "33": "Tratado de Tantauco",
  "34": "Constitución Liberal",
  "35": "Batalla de Lircay",
  "36": "El Peso de la Noche",
  "37": "Descubrimiento Chañarcillo",
  "38": "Constitución de 1833",
  "39": "Guerra Confederación",
  "40": "Batalla de Yungay",
  "41": "Ley de Colonización",
  "42": "Toma del Estrecho",
  "43": "Universidad de Chile",
  "44": "Reconocimiento España",
  "45": "Código Civil",
  "46": "Primer Ferrocarril",
  "47": "Revolución de 1851",
  "48": "El Telégrafo",
  "49": "Cuestión del Sacristán",
  "50": "Ley Instrucción Primaria",
  "51": "Fusión Liberal-Conservadora",
  "52": "El Cuerpo de Bomberos",
  "53": "Guerra contra España",
  "54": "Fin Reelección Inmediata",
  "55": "Reforma Electoral",
  "56": "Decreto Amunátegui",
  "57": "Guerra del Pacífico",
  "58": "Combate de Angamos",
  "59": "Tratado de Límites",
  "60": "Toma de Lima",
  "61": "Batalla de la Concepción",
  "62": "Ley de Cementerios",
  "63": "Ley de Matrimonio Civil",
  "64": "Ley Registro Civil",
  "65": "Anexión Isla de Pascua",
  "66": "Pontificia Univ. Católica",
  "67": "El Viaducto del Malleco",
  "68": "Guerra Civil de 1891",
  "69": "Batalla de Placilla",
  "70": "La Comuna Autónoma",
  "71": "Alumbrado Eléctrico",
  "72": "Cine en Chile",
  "73": "El Tranvía Eléctrico",
  "74": "Matanza Escuela Santa Maria",
  "75": "Centenario de Chile",
  "76": "Combate Naval de Iquique",
  "77": "Cuestión Social",
  "78": "Constitución Moralista 1823",
  "79": "Constitución Liberal 1828",
  "80": "Constitución de 1833",
};

const pistasData = {
  "01": ["Primera incursión española masiva en Chile.", "La expedición vino directamente desde el Cusco.", "El objetivo era explorar el territorio por primera vez."],
  "02": ["Ciudad fundada bajo el nombre de Santiago de la Nueva Extremadura.", "Es el hito que da inicio al asentamiento en el valle central.", "Se convirtió en el centro administrativo del país."],
  "03": ["Ataque indígena que redujo la ciudad a cenizas meses tras su fundación.", "El asalto fue liderado por el cacique Michimalonco.", "Obligó a los habitantes a reconstruir todo desde cero."],
  "04": ["Establecimiento de un fuerte militar clave en la zona del Biobío.", "Buscaba consolidar la presencia española hacia el sur.", "Fue una fundación estratégica para la guerra de Arauco."],
  "05": ["Derrota española donde muere el gobernador Valdivia.", "El enfrentamiento ocurrió en la zona de Tucapel.", "Fue uno de los golpes más duros para la conquista española."],
  "06": ["Combate donde el guerrero Galvarino es capturado y mutilado.", "Sucedió en las cercanías de las lagunas del sur.", "Es recordado por la resistencia física y valentía del guerrero."],
  "07": ["Victoria mapuche que obliga a los españoles a abandonar el sur.", "Este evento marcó el fin de la expansión española hacia el territorio austral.", "Fijó una frontera que duraría por siglos."],
  "08": ["Dinero enviado desde el Potosí para mantener al ejército profesional.", "Eran los recursos necesarios para financiar la guerra permanente.", "Venía de las minas de plata más ricas del continente."],
  "09": ["Ley que permitía esclavizar a indígenas capturados en guerra.", "Fue una normativa aplicada durante los periodos de mayor conflicto.", "Trataba a los prisioneros como propiedad de sus captores."],
  "10": ["Tratado de paz que reconoció la soberanía mapuche al sur del Biobío.", "Fue una reunión diplomática histórica entre ambos bandos.", "Se estableció un límite territorial respetado por el Rey."],
  "11": ["Sismo que destruyó casi todo Santiago durante la Colonia.", "Es recordado como el terremoto más devastador de esa etapa.", "Cambió la arquitectura de la capital para siempre."],
  "12": ["Sistema de trabajo agrícola en las grandes haciendas.", "Los trabajadores vivían y laboraban dentro de las tierras del patrón.", "Fue la base de la estructura social del campo chileno."],
  "13": ["Salida forzosa de la orden religiosa más rica y educada de Chile.", "Sus bienes fueron confiscados por orden directa del Rey.", "Dejaron un vacío importante en la educación y la economía local."],
  "14": ["Fin del sistema de servicio personal indígena.", "Marcó el cierre de una forma de tributo laboral muy antigua.", "Fue una reforma social importante antes de la independencia."],
  "15": ["Mejora de la conectividad entre la capital y el puerto principal.", "Se enfocó en facilitar el tránsito de mercancías y personas al mar.", "Fue la obra vial más relevante del final de la colonia."],
  "16": ["Organización de cabildo abierto tras la captura del Rey de España.", "Fue el primer paso formal hacia la autonomía nacional.", "Se formó un cuerpo de gobierno local por primera vez."],
  "17": ["Creación del poder legislativo chileno.", "Fue la primera vez que se reunieron representantes para hacer leyes.", "Marcó el inicio de la institucionalidad republicana."],
  "18": ["Ley que decretó que los hijos de esclavos nacen libres.", "Fue un paso fundamental hacia la dignidad humana en el país.", "Chile fue pionero en aplicar esta medida en la región."],
  "19": ["Publicación del primer periódico nacional.", "Su objetivo era difundir las ideas de libertad y educación.", "Es el hito fundacional de la prensa escrita en Chile."],
  "20": ["Primera carta fundamental que limitaba el poder del gobernante.", "Se redactó para organizar el país durante la Patria Vieja.", "Establecía reglas claras para quienes ejercían el mando."],
  "21": ["Creación de la institución educativa más antigua del país.", "Se fundó para ser el foco de luz y conocimiento de la nación.", "Ha formado a los líderes más importantes de nuestra historia."],
  "22": ["Derrota que da inicio al periodo de Reconquista Española.", "Los patriotas tuvieron que abandonar el territorio tras la batalla.", "Ocurrió en una ciudad del sur y fue un desastre militar."],
  "23": ["Regimiento español famoso por su crueldad en la represión.", "Actuaron durante el tiempo en que el Rey recuperó el mando.", "Su nombre era sinónimo de miedo para los partidarios de la libertad."],
  "24": ["Red de espías que enviaba información al Ejército de los Andes.", "Fue clave para preparar el regreso de los patriotas desde el exilio.", "Se basaba en el sigilo y la astucia de informantes locales."],
  "25": ["Victoria que permite el regreso de los patriotas a Santiago.", "Ocurrió tras el cruce de la cordillera en los cerros de Chacabuco.", "Fue el triunfo que puso fin a la ocupación española."],
  "26": ["Acta oficial firmada que declara a Chile como estado libre.", "Es el documento que formaliza la soberanía ante el mundo.", "Fue jurada con solemnidad para marcar el nacimiento de la nación."],
  "27": ["Hito bélico definitivo que expulsa a los realistas de la zona central.", "Ocurrió en los llanos cercanos a la capital.", "Selló para siempre la independencia del corazón del país."],
  "28": ["Operación naval para capturar los fuertes del sur.", "Buscaba expulsar a los españoles de sus últimos refugios costeros.", "Fue una hazaña marítima que aseguró el control del litoral."],
  "29": ["Renuncia del Director Supremo para evitar guerra civil.", "Fue un gesto de desprendimiento del poder por el bien del país.", "Marcó el fin del gobierno de quien proclamó la independencia."],
  "30": ["Chile se convierte en el primer país de América en prohibirla totalmente.", "Fue una medida que otorgó libertad absoluta a todos los habitantes.", "Terminó con la propiedad de una persona sobre otra."],
  "31": ["Intento de ley que regulaba la vida privada de los ciudadanos.", "Era una constitución que buscaba premiar la virtud y el buen comportamiento.", "Fue abandonada por ser demasiado estricta e impracticable."],
  "32": ["Intento de dividir a Chile en provincias autónomas.", "Se buscaba repartir el poder que estaba concentrado en Santiago.", "Fue una experiencia de organización política que duró poco tiempo."],
  "33": ["Rendición española en Chiloé e incorporación de la isla a Chile.", "Marcó la expulsión definitiva de los últimos soldados del Rey.", "El territorio nacional se extendió oficialmente hacia el archipiélago."],
  "34": ["Ley que buscaba un equilibrio de poderes y libertades individuales.", "Fue una carta fundamental que representaba el pensamiento liberal.", "Intentó dar más derechos a las personas frente al Estado."],
  "35": ["Guerra civil que da la victoria definitiva a los conservadores.", "El enfrentamiento decisivo ocurrió en las cercanías del río Lircay.", "Cambió el rumbo político hacia un orden mucho más autoritario."],
  "36": ["Concepto de orden y autoridad impuesto por el ministro Portales.", "Se refería a la necesidad de una mano dura para estabilizar el país.", "Fue la base del pensamiento político durante gran parte del siglo XIX."],
  "37": ["Hallazgo de la mina de plata más grande del país.", "Fue el motor que enriqueció a la nación y modernizó el norte.", "El descubrimiento ocurrió en la zona de Chañarcillo."],
  "38": ["Carta que definió la estructura autoritaria de Chile por décadas.", "Otorgó un poder casi total al Presidente de la República.", "Fue la constitución que trajo la mayor estabilidad política."],
  "39": ["Conflicto contra Perú y Bolivia por el control del Pacífico.", "Se generó para evitar que la unión de los vecinos amenazara al país.", "Fue la primera gran guerra internacional de la república."],
  "40": ["Victoria final que disuelve la Confederación Perú-Boliviana.", "Ocurrió en tierras extranjeras y fue celebrada con gran orgullo.", "Marcó el liderazgo de Chile en la región sur del continente."],
  "41": ["Plan para traer inmigrantes europeos al sur de Chile.", "Se buscaba poblar y producir en tierras que estaban aisladas.", "Dio origen a la influencia cultural alemana en zonas como Valdivia."],
  "42": ["Expedición de la Goleta Ancud para soberanía en el extremo sur.", "Fue la misión que permitió tomar posesión del Estrecho de Magallanes.", "Aseguró que la punta sur del continente fuera territorio chileno."],
  "43": ["Refundación de la educación superior en Chile.", "Se creó para ser el centro de la investigación y las letras nacionales.", "Su sede principal es un edificio icónico en la Alameda."],
  "44": ["Tratado donde España reconoce finalmente la independencia de Chile.", "Fue el reconocimiento diplomático oficial de la antigua metrópoli.", "Cerró formalmente el capítulo de la lucha contra el reino español."],
  "45": ["Redacción de las leyes que regulan los contratos y la propiedad.", "Es el cuerpo legal que ordena la vida civil de todos los chilenos.", "Sigue siendo la base de nuestro sistema jurídico actual."],
  "46": ["Inauguración de la vía Copiapó-Caldera.", "Fue el primer camino de hierro que funcionó en el país.", "Marcó el inicio de la era tecnológica del transporte a vapor."],
  "47": ["Guerra civil tras la elección de Manuel Montt.", "Fue un conflicto interno donde se cuestionó el mando presidencial.", "Hubo enfrentamientos armados entre facciones de ciudadanos."],
  "48": ["Primera línea de comunicación rápida entre Santiago y Valparaíso.", "Usaba señales eléctricas para enviar mensajes de forma inmediata.", "Fue la gran revolución tecnológica de mediados de siglo."],
  "49": ["Conflicto entre la Iglesia y el Estado por un despido en la Catedral.", "Un problema administrativo menor terminó escalando a nivel político.", "Provocó el quiebre de los grupos que apoyaban al gobierno."],
  "50": ["Estado garantiza educación básica gratuita para todos.", "Fue el compromiso legal para asegurar que cada niño aprenda a leer.", "Marcó el inicio de la instrucción primaria masiva en el país."],
  "51": ["Alianza política para democratizar el país.", "Fue la unión de grupos opuestos para enfrentar al gobierno autoritario.", "Buscaba modernizar las leyes y dar más libertad política."],
  "52": ["Fundación del primer cuerpo de voluntarios en Valparaíso/Santiago.", "Se organizó para combatir los incendios que asolaban las ciudades.", "Es una de las instituciones más respetadas por su servicio social."],
  "53": ["Conflicto por la defensa de Perú; bombardeo de Valparaíso.", "Una flota extranjera atacó el puerto principal en un acto de agresión.", "Unió a los países del Pacífico contra una amenaza europea."],
  "54": ["Reforma que prohíbe al presidente gobernar dos periodos seguidos.", "Se hizo para evitar que una sola persona se mantuviera mucho tiempo en el mando.", "Buscaba la alternancia en el poder y la renovación política."],
  "55": ["Se elimina el requisito de riqueza para votar; voto censitario.", "Permitió que más ciudadanos participaran en las elecciones.", "Fue un paso adelante en la democratización del sistema electoral."],
  "56": ["Permite el ingreso de las mujeres a la Universidad.", "Fue un hito histórico para la igualdad de género en la educación.", "Abrió las puertas de la ciencia y las letras a las chilenas."],
  "57": ["Inicio del conflicto por el salitre contra Perú y Bolivia.", "Fue la guerra más extensa y transformadora del territorio norte.", "Se originó por el control de las minas del 'oro blanco'."],
  "58": ["Captura del monitor Huáscar por la marina chilena.", "Fue un momento decisivo para ganar el control del mar en la guerra.", "Ocurrió frente a la costa de Angamos."],
  "59": ["Acuerdo con Argentina para definir la frontera en la cordillera.", "Se pactó para evitar conflictos por los límites territoriales al este.", "Estableció que las altas cumbres dividirían a ambos países."],
  "60": ["Ocupación de la capital peruana por tropas chilenas.", "Marcó una fase avanzada de la Guerra del Pacífico.", "El ejército nacional administró la ciudad durante la ocupación."],
  "61": ["Heroica resistencia de 77 soldados chilenos en la sierra peruana.", "Defendieron su posición hasta el final sin rendirse ante un ejército superior.", "Se recuerda como el sacrificio máximo en el combate de La Concepción."],
  "62": ["Permite enterrar a no católicos en cementerios públicos.", "Fue una de las leyes laicas que generó gran debate en la sociedad.", "Aseguró la dignidad en la muerte para personas de toda creencia."],
  "63": ["El Estado reconoce el matrimonio legal fuera de la iglesia.", "Permitió que la validez del vínculo dependiera de la ley civil.", "Fue un cambio fundamental en la vida familiar del país."],
  "64": ["El Estado asume el registro de nacimientos y defunciones.", "Quitó el control de estos datos a las instituciones religiosas.", "Creó la base de lo que hoy es la identidad oficial de cada ciudadano."],
  "65": ["Incorporación de Rapa Nui a la soberanía nacional.", "El territorio polinésico pasó a ser oficialmente parte de Chile.", "Se realizó mediante un acuerdo de protección y posesión."],
  "66": ["Fundación de la casa de estudios por parte de la Iglesia.", "Se creó para ofrecer una alternativa de educación superior católica.", "Es hoy una de las universidades más importantes de la capital."],
  "67": ["Gran obra de ingeniería ferroviaria en el sur de Chile.", "Es un puente de hierro icónico que cruza un río profundo.", "Permitió conectar el territorio austral a través del tren."],
  "68": ["Conflicto entre el Presidente y el Congreso por el poder.", "Terminó en una violenta guerra civil que dividió a la nación.", "Fue la lucha definitiva por quién debía mandar realmente en el país."],
  "69": ["Victoria del Congreso que marca el fin de Balmaceda.", "Fue la batalla que decidió el desenlace de la guerra civil de 1891.", "Ocurrió en la localidad de Placilla."],
  "70": ["Ley que dio independencia económica y política a los municipios.", "Buscaba descentralizar el mando que tenía el gobierno central.", "Permitió que las ciudades empezaran a gestionarse solas."],
  "71": ["Santiago comienza a iluminarse con energía eléctrica.", "Fue el adiós definitivo a los antiguos faroles de gas.", "Cambió la vida nocturna y la seguridad de la capital."],
  "72": ["Primera exhibición cinematográfica en Santiago.", "Las personas vieron por primera vez imágenes en movimiento.", "Fue el inicio de la era del cine en territorio nacional."],
  "73": ["Modernización del transporte público en la capital.", "Se introdujeron carros eléctricos para mover a los pasajeros.", "Reemplazaron a los antiguos carros tirados por caballos."],
  "74": ["Trágica represión contra huelguistas del salitre en Iquique.", "Cientos de trabajadores y sus familias fueron atacados en una escuela.", "Es uno de los episodios más tristes de la historia social chilena."],
  "75": ["Grandes fiestas y monumentos para celebrar 100 años de libertad.", "Se conmemoró el primer siglo de la independencia nacional.", "La ciudad se llenó de obras y celebraciones masivas."],
  "76": ["Dos naves se enfrentaron en aguas del norte. La más pequeña resistió hasta el último cañonazo antes de hundirse.", "Ocurrió durante una guerra en que Chile enfrentó a sus vecinos del norte por el control de un mineral muy valioso.", "El comandante de la nave menor no abandonó su puesto ni su bandera, aunque sabía que no podía ganar."],
  "77": ["Miles de familias vivían hacinadas sin agua limpia ni atención médica, mientras el país producía una riqueza enorme.", "Sucedió cuando el norte de Chile era el centro económico del país, entre fines del siglo XIX y comienzos del XX.", "Fueron hombres y mujeres trabajadores que se unieron, marcharon y pararon sus labores para exigir un trato justo."],
  "78": ["Se redactó un documento tan exigente que quería regular hasta las costumbres privadas de las personas. Nadie pudo cumplirlo.", "Fue en los primeros años del país como nación independiente, cuando aún se buscaba cómo organizarse.", "Lo redactó un político y jurista que soñaba con una república perfecta, ordenada hasta en sus más mínimos detalles."],
  "79": ["Un documento buscó repartir el poder entre distintas autoridades, proteger los derechos de las personas y crear un cargo para gobernar el país.", "Nació en una época de ideas nuevas y libertades, cuando muchos países de América recién estrenaban su independencia.", "Fue impulsado por pensadores que creían en la libertad, la igualdad y que el Congreso debía tener más poder que el gobernante."],
  "80": ["Tras años de desorden, se creó un documento que puso al mando a un gobernante muy poderoso y que solo algunos podían votar.", "Se dictó poco después de que un bando derrotara a otro en una guerra civil, imponiendo su visión de cómo debía ser el país.", "Detrás de él estaba un ministro muy influyente que creía en el orden, la autoridad fuerte y el rol de la Iglesia en el Estado."],
};

const respuestasData = {
  "01": { anio: "1536", evento: "Expedición de Almagro", personajes: "Diego de Almagro" },
  "02": { anio: "1541", evento: "Fundación de Santiago", personajes: "Pedro de Valdivia" },
  "03": { anio: "1541", evento: "Destrucción de Santiago", personajes: "Michimalonco" },
  "04": { anio: "1550", evento: "Fundación de Concepción", personajes: "Pedro de Valdivia" },
  "05": { anio: "1553", evento: "Batalla de Tucapel", personajes: "Lautaro, Pedro de Valdivia" },
  "06": { anio: "1557", evento: "Batalla de Lagunillas", personajes: "Galvarino, Garcia Hurtado de Mendoza" },
  "07": { anio: "1598", evento: "Desastre de Curalaba", personajes: "Pelantaro, Martin Garcia Onez de Loyola" },
  "08": { anio: "1600", evento: "Real Situado", personajes: "Felipe III" },
  "09": { anio: "1608", evento: "Esclavitud Indígena", personajes: "Felipe III" },
  "10": { anio: "1641", evento: "Parlamento de Quilín", personajes: "Marques de Baides" },
  "11": { anio: "1647", evento: "El Terremoto Magno", personajes: "Obispo Gaspar de Villarroel" },
  "12": { anio: "1700", evento: "El Inquilino", personajes: "Patrones y Peones" },
  "13": { anio: "1767", evento: "Expulsión Jesuitas", personajes: "Rey Carlos III" },
  "14": { anio: "1791", evento: "Abolición Encomienda", personajes: "Ambrosio OHiggins" },
  "15": { anio: "1792", evento: "Camino Santiago-Valparaíso", personajes: "Ambrosio OHiggins" },
  "16": { anio: "1810", evento: "Primera Junta de Gobierno", personajes: "Mateo de Toro y Zambrano" },
  "17": { anio: "1811", evento: "Primer Congreso Nacional", personajes: "Juan Martinez de Rozas" },
  "18": { anio: "1811", evento: "Libertad de Vientre", personajes: "Manuel de Salas" },
  "19": { anio: "1812", evento: "La Aurora de Chile", personajes: "Fray Camilo Henriquez" },
  "20": { anio: "1812", evento: "Reglamento Constitucional", personajes: "Jose Miguel Carrera" },
  "21": { anio: "1813", evento: "Fundación Inst. Nacional", personajes: "Jose Miguel Carrera" },
  "22": { anio: "1814", evento: "Desastre de Rancagua", personajes: "Bernardo OHiggins" },
  "23": { anio: "1815", evento: "Los Talaveras", personajes: "Vicente San Bruno" },
  "24": { anio: "1816", evento: "Espionaje Patriota", personajes: "Manuel Rodriguez" },
  "25": { anio: "1817", evento: "Batalla de Chacabuco", personajes: "Jose de San Martin" },
  "26": { anio: "1818", evento: "Proclamación Independencia", personajes: "Bernardo OHiggins" },
  "27": { anio: "1818", evento: "Batalla de Maipú", personajes: "OHiggins y San Martin" },
  "28": { anio: "1820", evento: "Toma de Valdivia", personajes: "Lord Thomas Cochrane" },
  "29": { anio: "1823", evento: "Abdicación de OHiggins", personajes: "Bernardo OHiggins" },
  "30": { anio: "1823", evento: "Abolición Esclavitud", personajes: "Jose Miguel Infante" },
  "31": { anio: "1823", evento: "Constitución Moralista", personajes: "Juan Egana" },
  "32": { anio: "1826", evento: "Leyes Federales", personajes: "Jose Miguel Infante" },
  "33": { anio: "1826", evento: "Tratado de Tantauco", personajes: "Ramon Freire" },
  "34": { anio: "1828", evento: "Constitución Liberal", personajes: "Jose Joaquin de Mora" },
  "35": { anio: "1830", evento: "Batalla de Lircay", personajes: "Jose Joaquin Prieto" },
  "36": { anio: "1831", evento: "El Peso de la Noche", personajes: "Diego Portales" },
  "37": { anio: "1832", evento: "Descubrimiento Chañarcillo", personajes: "Juan Godoy" },
  "38": { anio: "1833", evento: "Constitución de 1833", personajes: "Mariano Egana" },
  "39": { anio: "1836", evento: "Guerra Confederación", personajes: "Diego Portales" },
  "40": { anio: "1839", evento: "Batalla de Yungay", personajes: "Manuel Bulnes" },
  "41": { anio: "1842", evento: "Ley de Colonización", personajes: "Manuel Bulnes" },
  "42": { anio: "1843", evento: "Toma del Estrecho", personajes: "Juan Williams" },
  "43": { anio: "1843", evento: "Universidad de Chile", personajes: "Andres Bello" },
  "44": { anio: "1844", evento: "Reconocimiento España", personajes: "Isabel II de Espana" },
  "45": { anio: "1848", evento: "Código Civil", personajes: "Andres Bello" },
  "46": { anio: "1851", evento: "Primer Ferrocarril", personajes: "William Wheelwright" },
  "47": { anio: "1851", evento: "Revolución de 1851", personajes: "Manuel Montt" },
  "48": { anio: "1852", evento: "El Telégrafo", personajes: "William Wheelwright" },
  "49": { anio: "1856", evento: "Cuestión del Sacristán", personajes: "Manuel Montt" },
  "50": { anio: "1860", evento: "Ley Instrucción Primaria", personajes: "Manuel Montt" },
  "51": { anio: "1861", evento: "Fusión Liberal-Conservadora", personajes: "Jose Joaquin Perez" },
  "52": { anio: "1863", evento: "El Cuerpo de Bomberos", personajes: "Ciudadania" },
  "53": { anio: "1866", evento: "Guerra contra España", personajes: "Jose Joaquin Perez" },
  "54": { anio: "1871", evento: "Fin Reelección Inmediata", personajes: "Federico Errazuriz Z." },
  "55": { anio: "1874", evento: "Reforma Electoral", personajes: "Federico Errazuriz Z." },
  "56": { anio: "1877", evento: "Decreto Amunátegui", personajes: "Miguel Luis Amunategui" },
  "57": { anio: "1879", evento: "Guerra del Pacífico", personajes: "Anibal Pinto" },
  "58": { anio: "1879", evento: "Combate de Angamos", personajes: "Juan Jose Latorre" },
  "59": { anio: "1881", evento: "Tratado de Límites", personajes: "Domingo Santa Maria" },
  "60": { anio: "1881", evento: "Toma de Lima", personajes: "Manuel Baquedano" },
  "61": { anio: "1882", evento: "Batalla de la Concepción", personajes: "Ignacio Carrera Pinto" },
  "62": { anio: "1883", evento: "Ley de Cementerios", personajes: "Domingo Santa Maria" },
  "63": { anio: "1884", evento: "Ley de Matrimonio Civil", personajes: "Domingo Santa Maria" },
  "64": { anio: "1884", evento: "Ley Registro Civil", personajes: "Domingo Santa Maria" },
  "65": { anio: "1888", evento: "Anexión Isla de Pascua", personajes: "Policarpo Toro" },
  "66": { anio: "1888", evento: "Pontificia Univ. Católica", personajes: "Joaquin Larrain G." },
  "67": { anio: "1890", evento: "El Viaducto del Malleco", personajes: "Jose Manuel Balmaceda" },
  "68": { anio: "1891", evento: "Guerra Civil de 1891", personajes: "Jose Manuel Balmaceda" },
  "69": { anio: "1891", evento: "Batalla de Placilla", personajes: "Estanislao del Canto" },
  "70": { anio: "1892", evento: "La Comuna Autónoma", personajes: "Manuel Jose Irarrazaval" },
  "71": { anio: "1895", evento: "Alumbrado Eléctrico", personajes: "Ciudadania" },
  "72": { anio: "1896", evento: "Cine en Chile", personajes: "Ciudadania" },
  "73": { anio: "1900", evento: "El Tranvía Eléctrico", personajes: "Ciudadania" },
  "74": { anio: "1907", evento: "Matanza Escuela Santa Maria", personajes: "Pedro Montt" },
  "75": { anio: "1910", evento: "Centenario de Chile", personajes: "Emiliano Figueroa" },
  "76": { anio: "1879", evento: "Combate Naval de Iquique", personajes: "Arturo Prat, Miguel Grau" },
  "77": { anio: "1880", evento: "Cuestión Social", personajes: "Luis Emilio Recabarren" },
  "78": { anio: "1823", evento: "Constitución Moralista 1823", personajes: "Juan Egaña" },
  "79": { anio: "1828", evento: "Constitución Liberal 1828", personajes: "Francisco Antonio Pinto, Melchor de Santiago Concha" },
  "80": { anio: "1833", evento: "Constitución de 1833", personajes: "Diego Portales, Mariano Egaña, Manuel José Gandarillas" },
};

const eraData = {
  "01": "Conquista",       "02": "Conquista",       "03": "Conquista",
  "04": "Conquista",       "05": "Conquista",       "06": "Conquista",
  "07": "Conquista",       "08": "Colonia",         "09": "Colonia",
  "10": "Colonia",         "11": "Colonia",         "12": "Colonia",
  "13": "Colonia",         "14": "Colonia",         "15": "Colonia",
  "16": "Independencia",   "17": "Independencia",   "18": "Independencia",
  "19": "Independencia",   "20": "Independencia",   "21": "Independencia",
  "22": "Independencia",   "23": "Reconquista",     "24": "Reconquista",
  "25": "Independencia",   "26": "Independencia",   "27": "Independencia",
  "28": "Independencia",   "29": "Independencia",   "30": "Independencia",
  "31": "Organización",    "32": "Organización",    "33": "Organización",
  "34": "Organización",    "35": "Organización",    "36": "Rep. Conservadora",
  "37": "Rep. Conservadora","38": "Rep. Conservadora","39": "Rep. Conservadora",
  "40": "Rep. Conservadora","41": "Rep. Conservadora","42": "Rep. Conservadora",
  "43": "Rep. Conservadora","44": "Rep. Conservadora","45": "Rep. Conservadora",
  "46": "Rep. Conservadora","47": "Rep. Conservadora","48": "Rep. Conservadora",
  "49": "Rep. Conservadora","50": "Rep. Conservadora","51": "Rep. Liberal",
  "52": "Rep. Liberal",    "53": "Rep. Liberal",    "54": "Rep. Liberal",
  "55": "Rep. Liberal",    "56": "Rep. Liberal",    "57": "Rep. Liberal",
  "58": "Rep. Liberal",    "59": "Rep. Liberal",    "60": "Rep. Liberal",
  "61": "Rep. Liberal",    "62": "Rep. Liberal",    "63": "Rep. Liberal",
  "64": "Rep. Liberal",    "65": "Rep. Liberal",    "66": "Rep. Liberal",
  "67": "Rep. Liberal",    "68": "Rep. Liberal",    "69": "Rep. Liberal",
  "70": "Parlamentarismo", "71": "Parlamentarismo", "72": "Parlamentarismo",
  "73": "Parlamentarismo", "74": "Parlamentarismo", "75": "Parlamentarismo",
  "76": "Rep. Liberal",    "77": "Rep. Liberal",    "78": "Organización",
  "79": "Organización",    "80": "Organización",
};

// ── SEED ─────────────────────────────────────────────────────────────────────

async function seed() {
  const colRef = db.collection("cartas");
  const batch = db.batch();
  let count = 0;

  for (const id of Object.keys(baseNombres)) {
    const docRef = colRef.doc(`carta_${id}`);
    batch.set(docRef, {
      id,
      nombre_archivo: baseNombres[id],
      evento: eventosData[id],
      era: eraData[id],
      anio: respuestasData[id].anio,
      personajes: respuestasData[id].personajes,
      pistas: pistasData[id],
      tiene_imagen: true,
      tiene_audio: true,
    });
    count++;
  }

  await batch.commit();
  console.log(`✅ ${count} cartas escritas en Firestore (colección: cartas)`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Error al poblar Firestore:", err);
  process.exit(1);
});
